apiVersion: apps/v1
kind: Deployment
metadata:
  name: s06-web
  labels:
    app: s06-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: s06-web
      tier: frontend
  template:
    metadata:
      labels:
        app: s06-web
        tier: frontend
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
