apiVersion: apps/v1
kind: Deployment
metadata:
  name: s07-web
  labels:
    app: s07-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s07-web
  template:
    metadata:
      labels:
        app: s07-web
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
