apiVersion: apps/v1
kind: Deployment
metadata:
  name: s01-whoami
  labels:
    app: s01-whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s01-whoami
  template:
    metadata:
      labels:
        app: s01-whoami
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
